### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by axhx** [Reshav-Paul/grodudes_app#4] opened 2021-01-14 09:33 UTC
1. When registering for new account its registering sucessfully but while logging in with same username and password its not logging in and showing some error as : "An error occurred while trying to login" and "login failed.please try again". Although I give correct username and password its showing like this.

2. And while we close and open the application, the login data are gone and again it asks for the login or signup.

Please help me recover this issue.

**Comment by Reshav-Paul** [comment] 2021-01-14 09:55
I tried to register a new user and also logged in and out several times. There is no issue from the app.

Please use postman and use the API to test the login endpoint of your WooCommerce app. Check if it is actually working. If it is working then debug the dart code and the http responses. As I said I am not working on this app anymore.

Since I could not reproduce the issue I will be closing this.

**Closed as completed by Reshav-Paul** 2021-01-14 09:55 UTC
